export const myBooks = [
    {
        "id": "Dl2rzkHKmvQVCg8P6lVD",
        "bookId": "book_1706741630951",
        "createdAt": {
            "seconds": 1706741649,
            "nanoseconds": 535000000
        },
        "userId": "KtAsHWHSvmfJGHfGe61TIcNFAn83",
        "imageUrls": [
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706741630951%2Fundefined?alt=media&token=dccd7c02-98a4-4d67-80e2-449a22002b78",
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706741630951%2Fundefined?alt=media&token=0f5a04b9-b553-445b-9c39-672e7965526d",
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706741630951%2Fundefined?alt=media&token=1cb22fa9-a474-4a0d-b9ce-4b5a50f4348e"
        ],
        "story": "In the Enchanted Forest, a curious girl named Lily lived in a cozy cottage. Lily loved exploring the wonders of the forest, but she dreamed of uncovering something truly magical. One bright morning, she set out on an adventure, armed with her trusty journal and a heart full of excitement.\n\nAs Lily skipped through the tall grass, she stumbled upon a hidden path. With a twinkle in her eye, she decided to follow it, wondering where it might lead. The path twisted and turned, leading her deeper into the forest, until she reached a sparkling brook.\n\nSitting by the brook, Lily noticed a delicate, shimmering key lying on a mossy stone. Her curiosity piqued, she picked up the key and noticed a note attached. It read, \"This key unlocks the door to a world of imagination and wonder.\"\n\nWith butterflies in her stomach, Lily continued her journey, searching for the door that the key would unlock. Hours passed, and just as she began to lose hope, she spotted a peculiar door nestled amidst the trees. Its vibrant colors and intricate carvings revealed it to be the door of her dreams.\n\nTrembling with anticipation, Lily inserted the key into the tiny lock. With a magical click, the door creaked open, revealing a magnificent kingdom filled with mythical creatures and enchanted treasures. As she stepped inside, the forest came alive with dancing fairies and singing birds.\n\nEvery day became an adventure in the marvelous kingdom – she danced with unicorns, played hide-and-seek with mischievous elves, and listened to the wise stories of talking trees. The friends she made were as unique as the colors of the sunset, and their laughter filled the air with endless joy.\n\nBut as much as she cherished her newfound home, Lily realized that she missed her family and the comfort of her little cottage. With a heavy heart, she decided it was time to return to her own world and share the memories and magic she had discovered.\n\nWith a final goodbye, Lily bid farewell to the enchanted kingdom and stepped back through the door. As she walked back along the path, her heart felt lighter than ever before. When she returned to her cottage, she realized that her adventures would remain with her forever, reminding her to always cherish the beauty of the world around her.\n\nFrom that day forward, Lily's imagination brought endless wonder and joy into her life. And every time she gazed at the Enchanted Forest through her window, she smiled, knowing that magic awaited those who believed.\n\n~The End~"
    },
    {
        "id": "N3oXkxIMITIVBrXwkEYX",
        "userId": "KtAsHWHSvmfJGHfGe61TIcNFAn83",
        "story": "Once upon a time, in a magical forest filled with towering trees and vibrant flowers, there lived a brave little girl named Lily. This enchanted forest was known as the Whispering Woods.\n\nLily had grown up in the Whispering Woods, surrounded by the gentle whispers of the trees and the cheerful songs of the birds. She had long curly hair, the color of fallen leaves, and big sparkling eyes that shone like the stars.\n\nEvery day, Lily would venture deep into the heart of the forest. She would embark on different adventures, exploring hidden caves, climbing moss-covered rocks, and chasing colorful butterflies that danced among the flowers. The animals of the Whispering Woods were her friends, and they would often accompany her on her playful journeys.\n\nOne sunny morning, as Lily was skipping along a sparkling brook, she noticed a glittering path leading into a dense part of the forest she had never seen before. Curiosity sparked within her, and with excitement in her heart, she followed the magical trail.\n\nAs she ventured deeper into the forest, the air grew colder, and the sunlight disappeared beneath the thick canopy of the tall trees. Moss covered the ground, forming a soft carpet beneath her feet.\n\nSuddenly, a melodious sound echoed through the trees—a sweet, enchanting melody that seemed to fill the entire forest. Lily followed the sound until she reached a small clearing. There, she discovered a group of fairies, each one more beautiful than the last, dressed in vibrant dresses made from flower petals.\n\nThe fairies welcomed Lily with open arms, inviting her to join their joyful dance. She spun and twirled, feeling the magic of the forest fill her soul. The fairies shared stories of the Whispering Woods and the magical creatures that dwelled within its depths.\n\nFrom that day on, Lily became the guardian of the Whispering Woods. She protected the plants and animals, ensuring their safety and harmony. With every passing adventure, she grew stronger and wiser, her bond with the forest deepening.\n\nYears rolled by, and Lily became known as the girl who shared a special bond with the Whispering Woods. Visitors from distant lands would come to seek her guidance, and she would share the tales of her beloved forest, captivating young and old alike.\n\nAnd so, the legacy of the girl forest, Lily, continued to thrive, spreading joy, magic, and wonder throughout the Whispering Woods, forever and always.\n\n~The End~",
        "createdAt": {
            "seconds": 1706751440,
            "nanoseconds": 472000000
        },
        "imageUrls": [
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706751422586%2Fundefined?alt=media&token=4de7c6e0-8aab-43bb-977e-bbf53ef91c31",
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706751422586%2Fundefined?alt=media&token=61a81965-8ab7-40eb-9985-680c758b914b",
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706751422586%2Fundefined?alt=media&token=162bb259-33f8-48db-8e59-cf2637f2a787"
        ],
        "bookId": "book_1706751422586"
    },
    {
        "id": "S3vzhlr5tjfpm1WUGNT8",
        "story": "The Floating Fortress\n\nOnce upon a time in a faraway kingdom, there was a magical castle in the sky. This castle, known as the Floating Fortress, was a place where dreams came true and imaginations ran wild.\n\nPerched high above cotton candy clouds and guarded by shimmering unicorns, the castle was a sight to behold. Its walls sparkled with diamonds, reflecting the colors of the rainbow. And every night, as the moon painted the sky with its gentle glow, the castle lit up with a magical radiance that could be seen for miles.\n\nOne day, a young girl named Lily discovered the castle while exploring the enchanted forest. Fascinated by its beauty, she longed to unlock its secrets. With determination in her heart, she set off on an adventure to reach the castle.\n\nAs she entered the castle grounds, Lily couldn't help but feel a sense of wonder and awe. The air was filled with the sweet scent of flowers, and the sound of laughter echoed through the halls. The countless rooms held treasures beyond her wildest dreams - books that could transport her to far-off lands, statues that came to life with a simple touch, and paintings that revealed hidden worlds.\n\nIn the heart of the castle, Lily stumbled upon a grand hall filled with magical creatures. Fairies danced on tinkling chimes, while talking animals sat at a long table, feasting on a sumptuous banquet. The castle's inhabitants, both old and young, welcomed Lily with open arms, eager to share their stories and adventures.\n\nDays turned into weeks, and weeks into months, but Lily never tired of the mysteries and delights that the castle offered. She learned to fly on the back of a majestic Pegasus, chased fireflies through fields of dreams, and befriended a mischievous dragon named Flicker.\n\nOne afternoon, as the sun painted the sky with hues of gold and crimson, Lily realized it was time to return home. Though she would miss the castle and all its wondrous magic, she knew that her own world was waiting for her.\n\nWith a heavy heart, Lily bid farewell to the Floating Fortress and its extraordinary inhabitants. As she descended through the clouds, the castle became a shimmering speck in the distance, a memory she would cherish forever.\n\nBack in her village, Lily shared stories of her incredible adventure with wide-eyed children who listened intently. And as the tale spread, more children filled their dreams with visions of the magical castle in the sky.\n\nAnd so, the Floating Fortress continued to inspire and enchant generation after generation, reminding them that even in the vastness of the sky, dreams could manifest into reality and magic would forever dwell in the hearts of those who believed.\n\n~The End~",
        "userId": "KtAsHWHSvmfJGHfGe61TIcNFAn83",
        "bookId": "book_1706741973809",
        "createdAt": {
            "seconds": 1706741990,
            "nanoseconds": 76000000
        },
        "imageUrls": [
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706741973809%2Fundefined?alt=media&token=ea0f9724-e686-4720-bd67-80709e8d71f0",
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706741973809%2Fundefined?alt=media&token=88197410-eba6-42b5-905c-81bdd5b51d6f",
            "https://firebasestorage.googleapis.com/v0/b/story-60f4f.appspot.com/o/images%2FKtAsHWHSvmfJGHfGe61TIcNFAn83%2Fbook_1706741973809%2Fundefined?alt=media&token=c8385012-b73c-481e-a98a-38c6277e42a4"
        ]
    }
]